# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
	platform :ios, '11.0'
    project 'Demo.xcodeproj'
    workspace 'Demo.xcworkspace'
	pod 'Kiwi'
end
